# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/TP_DUBOIS/TP_Video chain/TP_Video chain.srcs/sources_1/bd/VGA_source/ip/VGA_source_inverter_0_0/VGA_source_inverter_0_0.xci
# IP: The module: 'VGA_source_inverter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/TP_DUBOIS/TP_Video chain/TP_Video chain.srcs/sources_1/bd/VGA_source/ip/VGA_source_inverter_0_0/constraints/inverter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_source_inverter_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/TP_DUBOIS/TP_Video chain/TP_Video chain.srcs/sources_1/bd/VGA_source/ip/VGA_source_inverter_0_0/VGA_source_inverter_0_0.xci
# IP: The module: 'VGA_source_inverter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/TP_DUBOIS/TP_Video chain/TP_Video chain.srcs/sources_1/bd/VGA_source/ip/VGA_source_inverter_0_0/constraints/inverter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_source_inverter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
